// Copyright (C) 2026 Chris Richardson
//
// This file is part of DOLFINx (https://www.fenicsproject.org)
//
// SPDX-License-Identifier: MIT
//

#include <algorithm>
#include <array>
#include <chrono>
#include <cmath>
#include <cstdint>
#include <iomanip>
#include <memory>
#include <numeric>
#include <ranges>
#include <span>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include <basix/finite-element.h>
#include <basix/interpolation.h>
#include <boost/program_options.hpp>
#include <dolfinx.h>
#include <dolfinx/fem/Constant.h>
#include <dolfinx/io/ADIOS2Writers.h>
#include <dolfinx/la/Vector.h>

#include <thrust/device_vector.h>
#include <thrust/execution_policy.h>
#include <thrust/fill.h>
#include <thrust/functional.h>
#include <thrust/inner_product.h>
#include <thrust/transform.h>

#include "../../include/gpu_geometry.h"
#include "body_force.h"
#include "cg.h"
#include "elasticity.h"
#include "p_multigrid.h"
#include "jacobi.h"
#include "util.h"

using namespace dolfinx;
namespace po = boost::program_options;

constexpr int highest_level = 3; // highest polynomial level to use in the multigrid hierarchy
constexpr int lowest_level = 2; // lowest polynomial level to use in the multigrid hierarchy
constexpr bool jacobi_cg = true; // use Jacobi preconditioner in CG


int main(int argc, char* argv[])
{
  MPI_Init(&argc, &argv);
  dolfinx::init_logging(argc, argv);

  po::options_description desc("Options");
  desc.add_options()("help,h", "Print usage message")(
      "n", po::value<std::size_t>()->default_value(100), "Cube mesh size");

  // Parse command line options
  po::variables_map vm;
  po::store(po::command_line_parser(argc, argv)
                .options(desc)
                .allow_unregistered()
                .run(),
            vm);

  {
    std::int32_t n = vm["n"].as<std::size_t>();
    std::cout << "n=" << n << "\n";
    auto part
        = mesh::create_cell_partitioner(dolfinx::mesh::GhostMode::none, 2);
    auto mesh = std::make_shared<mesh::Mesh<U>>(mesh::create_box<U>(
        MPI_COMM_WORLD, {{{0.0, 0.0, 0.0}, {1.0, 1.0, 1.0}}}, {n, n, n},
        mesh::CellType::tetrahedron, part));

    // Create list of all cells
    std::vector<std::int32_t> cell_list_host(
        mesh->topology()->index_map(mesh->topology()->dim())->size_local());
    std::iota(cell_list_host.begin(), cell_list_host.end(), 0);
    thrust::device_vector<std::int32_t> cell_list(cell_list_host.begin(),
                                                   cell_list_host.end());

    auto left_boundary = [](auto x){ // x is a table of coordinates
      std::vector<std::int8_t> marker(x.extent(1), false); // create a list called marker which has one entry for each point being checked
      // mark points on the left boundary (x=0) as true
      for (std::size_t p = 0; p < x.extent(1); ++p) // loop over all points
      {
        if (std::abs(x(0, p)) < 1e-8) // check if x coordiante is 0/close to 0
        {
          marker[p] = true; // mark this point as true
        }
      }
      return marker;
    };

    PMultigridHierarchy<highest_level, lowest_level> hierarchy(mesh, cell_list, left_boundary);

    // temp variables to keep rest of code working
    auto& fine_level = hierarchy.level;
    auto& coarser_level = hierarchy.coarser.level;
    // auto& P_device = hierarchy.interpolation;


    // -----------------------------------------------------------------------
    // Functions
    // -----------------------------------------------------------------------
    auto b = std::make_shared<fem::Function<T>>(fine_level.V);

    // const force [0 0 -0.001]
    auto body_force = std::make_shared<fem::Constant<T>>(std::array<T, 3>{T(0), T(0), T(-1e-3)});

    // attach runtime function space and force to the form generated by the body_force.py file
    fem::Form<T> load_form = fem::create_form<T>(
      *form_body_force_L, 
      {fine_level.V}, // test function space
      {}, // no coefficient function spaces
      {{"B", body_force}}, // UFL constant named B
      {}, {}
    );

    // start with 0 host vector for b
    std::ranges:: fill(b->x()->array(), T(0));
    // assemble b_i = integral(B * phi_i)dx for all i
    fem::assemble_vector(b->x()->array(), load_form);

    // set the clamped nodes to 0 in b
    for (std::int32_t node : fine_level.bc_nodes)
    {
      b->x()->array()[3 * node + 0] = T(0);
      b->x()->array()[3 * node + 1] = T(0);
      b->x()->array()[3 * node + 2] = T(0);
    }

    la::Vector<T, thrust::device_vector<T>> b_device(*(b->x()));
    using DeviceVector = decltype(b_device);

    // 0 initial guess
    DeviceVector x_device(fine_level.V->dofmap()->index_map, 3);
    thrust::fill(thrust::device, x_device.array().begin(), x_device.array().end(), T(0));

    // create CG solver
    elasticity::CGSolver<DeviceVector> cg_solver(fine_level.V->dofmap()->index_map, 3);
    cg_solver.set_max_iterations(2000);
    cg_solver.set_tolerance(T(1e-8));

    DeviceVector level_3_inverse_diagonal(fine_level.V->dofmap()->index_map, 3);
    thrust::fill(thrust::device, level_3_inverse_diagonal.array().begin(), level_3_inverse_diagonal.array().end(), T(0));
    
    fine_level.assemble_diagonal(level_3_inverse_diagonal);
    
    // convert diag(A) to diag(A)^{-1}
    thrust::transform(thrust::device, level_3_inverse_diagonal.array().begin(), level_3_inverse_diagonal.array().end(),
      fine_level.bc_marker.begin(), level_3_inverse_diagonal.array().begin(), invert_jacobi_diagonal<T>());

    if (jacobi_cg){
      // copy diag(A)^{-1} to CG solver
      cg_solver.set_diag_inverse(level_3_inverse_diagonal);
    }

    device_synchronize();


    // // testing jacobi smoother
    // DeviceVector x_smoother_test(level_3.V->dofmap()->index_map, 3);
    // DeviceVector level_3_Ax(level_3.V->dofmap()->index_map, 3);
    // DeviceVector level_3_residual(level_3.V->dofmap()->index_map, 3);

    // thrust::fill(thrust::device, x_smoother_test.array().begin(), x_smoother_test.array().end(), T(0));

    // const T residual_before = residual_norm(level_3, x_smoother_test, b_device, level_3_Ax, level_3_residual);
    // std::cout << "Residual norm before Jacobi smoothing = " << residual_before << "\n";

    // constexpr int jacobi_steps = 1;
    // constexpr T omega = T(0.3);

    // jacobi_smooth(level_3, x_smoother_test, b_device, level_3_inverse_diagonal, level_3_Ax, level_3_residual, jacobi_steps, omega);

    // const T residual_after = residual_norm(level_3, x_smoother_test, b_device, level_3_Ax, level_3_residual);
    // std::cout << "Residual norm after Jacobi smoothing = " << residual_after << "\n";


    // timing 
    constexpr int runs = 1;
    std::vector<double> times;
    times.reserve(runs);

    int iterations = 0;

    for (int i = 0; i < runs; ++i){
      thrust::fill(thrust::device, x_device.array().begin(), x_device.array().end(), T(0));
      device_synchronize();

      const auto start = std::chrono::high_resolution_clock::now();

      iterations = cg_solver.solve(fine_level, x_device, b_device, jacobi_cg);
      device_synchronize();

      const auto end = std::chrono::high_resolution_clock::now();

      const double seconds = std::chrono::duration<double>(end - start).count();
      times.push_back(seconds);
    }

    const double avg_time = std::accumulate(times.begin(), times.end(), 0.0) / runs;
    std::cout << "Average solve time = " << avg_time << " seconds\n";
    std::cout << "Number of iterations = " << iterations << "\n";


    auto x = std::make_shared<fem::Function<T>>(fine_level.V);

    thrust::copy(x_device.array().begin(), x_device.array().end(), x->x()->array().begin());
    thrust::copy(b_device.array().begin(), b_device.array().end(), b->x()->array().begin());

    std::cout << std::setprecision(17);

    std::cout << "Computed x norm = "
              << dolfinx::la::norm(*x->x()) << "\n";

    std::cout << "b norm = "
              << dolfinx::la::norm(*b->x()) << "\n";

              
    // test functions for interpolation from coarse to fine function space
    auto test_field = [](auto x)
        -> std::pair<std::vector<T>, std::vector<std::size_t>>
    {
      const std::size_t np = x.extent(1);
      std::vector<T> vals(3 * np, T(0));

      for (std::size_t p = 0; p < np; ++p)
      {
        const T X = x(0, p);
        const T Y = x(1, p);
        const T Z = x(2, p);

        vals[p]          = X * X + Y * Z;
        vals[np + p]     = Y * Y + X * Z;
        vals[2 * np + p] = Z * Z + X * Y;
      }

      return {vals, {3, np}};
    };    
    
    auto u_coarse = std::make_shared<fem::Function<T>>(coarser_level.V);
    auto u_fine = std::make_shared<fem::Function<T>>(fine_level.V);
    u_coarse->interpolate(test_field);
    u_fine->interpolate(test_field);

    la::Vector<T, thrust::device_vector<T>> coarse_device(*(u_coarse->x()));
    DeviceVector fine_from_coarse(fine_level.V->dofmap()->index_map, 3);
    thrust::fill(thrust::device, fine_from_coarse.array().begin(), fine_from_coarse.array().end(), T(0));

    // // testing prolongation //
    // const std::size_t num_cells = V->dofmap()->map().extent(0);
    // constexpr int transfer_threads = 256;
    // const std::size_t total_transfer_tasks = num_cells * fine_dofs_kernel * 3;
    // const std::size_t transfer_blocks = (total_transfer_tasks + transfer_threads - 1) / transfer_threads;

    // thrust::fill(thrust::device, fine_from_coarse.array().begin(), fine_from_coarse.array().end(), T(0));

    // p_transfer::prolong_cells<T, coarse_dofs_kernel, fine_dofs_kernel><<<static_cast<int>(transfer_blocks), transfer_threads>>>(
    //   num_cells,
    //   P_device.data().get(),
    //   gpu_dofmap_coarse.map().data().get(),
    //   gpu_dofmap.map().data().get(),
    //   coarse_device.array().data().get(),
    //   fine_from_coarse.array().data().get()
    // );

    // device_synchronize();

    // // get the exact values of the fine function
    // const auto fine_exact_values = u_fine->x()->array();

    // // copy the GPU result to host for comparison
    // std::vector<T> fine_from_coarse_host(fine_from_coarse.array().size());
    // thrust::copy(fine_from_coarse.array().begin(), fine_from_coarse.array().end(), fine_from_coarse_host.begin());

    // constexpr T tolerance = T(1e-12);
    // T max_error = T(0);
    // std::size_t failed_values = 0;

    // // loop over fine dofs and compare the computed values from the coarse function to the exact values from the fine function
    // for (std::size_t dof = 0; dof < fine_from_coarse_host.size(); ++dof)
    // {
    //   const T error = std::abs(fine_from_coarse_host[dof] - fine_exact_values[dof]);
    //   max_error = std::max(max_error, error);

    //   if (error > tolerance) failed_values++;
    // }

    // std::cout << std::scientific
    //           << std::setprecision(3)
    //           << "Maximum global prolongation error = "
    //           << max_error << '\n';

    // std::cout << "Number of failed values = "
    //           << failed_values << '\n';


    // // testing restriction //
    // DeviceVector coarse_restricted(V_coarse->dofmap()->index_map, 3);
    // thrust::fill(thrust::device, coarse_restricted.array().begin(), coarse_restricted.array().end(), T(0));

    // const std::size_t total_restrict_tasks = num_fine_nodes * 3;
    // const std::size_t restrict_blocks = (total_restrict_tasks + transfer_threads - 1) / transfer_threads;

    // p_transfer::restrict_nodes<T, coarse_dofs_kernel, fine_dofs_kernel><<<static_cast<int>(restrict_blocks), transfer_threads>>>(
    //   num_fine_nodes,
    //   P_device.data().get(),
    //   gpu_dofmap_coarse.map().data().get(),
    //   owner_cell_device.data().get(),
    //   owner_local_device.data().get(),
    //   fine_from_coarse.array().data().get(),
    //   coarse_restricted.array().data().get()
    // );

    // device_synchronize();

    // const T left = thrust::inner_product(thrust::device, fine_from_coarse.array().begin(), fine_from_coarse.array().end(),
    //   fine_from_coarse.array().begin(), T(0));
    // const T right = thrust::inner_product(thrust::device, coarse_device.array().begin(), coarse_device.array().end(),
    //   coarse_restricted.array().begin(), T(0));

    // const T difference = std::abs(left - right);
    // const T scale = std::max(std::max(T(1), std::abs(left)), std::abs(right));
    // const T relative_error = difference / scale;

    // std::cout << std::setprecision(8);
    // std::cout << "(Px, Px) = " << left << "\n";
    // std::cout << "(x, P^T Px) = " << right << "\n";
    // std::cout << "Relative error = " << relative_error << "\n";

    // ///// for visualisation in PARAVIEW /////
    // // dolfinx function to hold the prolonged values for visualisation
    // auto u_prolonged = std::make_shared<fem::Function<T>>(V);
    // // copy GPU result into dolfinx function
    // std::copy(fine_from_coarse_host.begin(), fine_from_coarse_host.end(), u_prolonged->x()->array().begin());
    
    // u_fine->name = "direct_fine";
    // u_prolonged->name = "prolonged_fine";
    
    // #ifdef HAS_ADIOS2
    // io::VTXWriter<U> transfer_writer(MPI_COMM_WORLD, "p_transfer.bp", {u_fine, u_prolonged}, "bp4");
    // transfer_writer.write(0.0);
    // #endif

    // x->name = "displacement";

    // #ifdef HAS_ADIOS2
    // io::VTXWriter<U> solution_writer(MPI_COMM_WORLD, "cantilever.bp", {x}, "bp4");

    // solution_writer.write(0.0);
    // #endif
  }

  MPI_Finalize();
  return 0;
}
